In [ ]:
import numpy as np

In [ ]:
arr = np.array([3,4,6,7,9,2])

In [ ]:
np.sum(arr)

31

In [ ]:
np.mean(arr), np.median(arr)

5.166666666666667

In [ ]:
np.sin(arr),np.cos(arr)

array([ 0.14112001, -0.7568025 , -0.2794155 ,  0.6569866 ,  0.41211849,
        0.90929743])

In [ ]:
np.min(arr),np.max(arr)

2

#Numerical operations on 2D array

In [ ]:
arr = np.array([[4,6,2,4],[9,7,1,0],[3,1,0,9],[4,3,7,1]])
print(arr)

[[4 6 2 4]
 [9 7 1 0]
 [3 1 0 9]
 [4 3 7 1]]


In [ ]:
np.max(arr)

9

In [ ]:
np.max(arr,axis = 0)

array([9, 7, 7, 9])

In [ ]:
np.max(arr, axis = 1)

array([6, 9, 9, 7])

In [ ]:
np.sum(arr), np.sum(arr, axis = 0) ,  np.sum(arr, axis = 1)

(61, array([20, 17, 10, 14]), array([16, 17, 13, 15]))

#Pracctice code :

Create 2d array having shape 4*4

create array that contains average of all columns.

get the sum of all the averages

In [ ]:
arr = np.array([[4,6,2,4],[9,7,1,0],[3,1,0,9],[4,3,7,1]])
print(arr)

[[4 6 2 4]
 [9 7 1 0]
 [3 1 0 9]
 [4 3 7 1]]


In [ ]:
x = np.mean(arr, axis = 0)

In [ ]:
sum(x)

15.25

In [ ]:
sum(np.mean(arr, axis = 0))

15.25

In [ ]:
arr2 = np.array([[4,7,1],[8,1,3],[7,1,3]])
print(arr2)

[[4 7 1]
 [8 1 3]
 [7 1 3]]


In [ ]:
arr2 = arr2 + 10

In [ ]:
arr2

array([[14, 17, 11],
       [18, 11, 13],
       [17, 11, 13]])

In [ ]:
arr3 = np.array([[5,10,5],[10,5,10],[10,10,20]])
print(arr3)

[[ 5 10  5]
 [10  5 10]
 [10 10 20]]


In [ ]:
arr2 * arr3

array([[ 70, 170,  55],
       [180,  55, 130],
       [170, 110, 260]])

#Practice code

create 2d array with shape 4*4

find columnwise minimum and store value in l1

create another 2d array with shape 4*4

find row wise average and store value in l2


perform multiplication between l1 and l2

In [ ]:
arr1 = np.array([[5,2,7,0],[1,8,2,6],[6,3,2,1],[9,6,4,1]])
print(arr1)

[[5 2 7 0]
 [1 8 2 6]
 [6 3 2 1]
 [9 6 4 1]]


In [ ]:
l1 = np.min(arr1,axis =0)
print(l1)

[1 2 2 0]


In [ ]:
arr2 = np.array([[4,2,5,7],[9,8,7,6],[1,2,3,4],[0,3,1,5]])
print(arr2)

[[4 2 5 7]
 [9 8 7 6]
 [1 2 3 4]
 [0 3 1 5]]


In [ ]:
l2 = np.mean(arr2, axis = 1)
print(l2)

In [ ]:
l1 * l2

[4.5  7.5  2.5  2.25]


In [ ]:
#Broadcasting operations
arr1 = np.array([[4,2,5,7],[9,8,7,6],[1,2,3,4],[0,3,1,5]])
print(arr1)

arr2 = np.array([40,40,40,40])
print(arr2)

[[4 2 5 7]
 [9 8 7 6]
 [1 2 3 4]
 [0 3 1 5]]
[40 40 40 40]


In [ ]:
arr1 + arr2

array([[44, 42, 45, 47],
       [49, 48, 47, 46],
       [41, 42, 43, 44],
       [40, 43, 41, 45]])

In [ ]:
col  = np.array([[30],[40],[50],[60]])

In [ ]:
print(col)

[[30]
 [40]
 [50]
 [60]]


In [ ]:
arr1 + col

array([[34, 32, 35, 37],
       [49, 48, 47, 46],
       [51, 52, 53, 54],
       [60, 63, 61, 65]])