#Numpy

In [24]:
import numpy as np

In [25]:
l =[4,2,5,7,8,5]

In [26]:
arr = np.array([4,3,5,7,8,6])

In [27]:
print(arr)

[4 3 5 7 8 6]


In [28]:
print(l)

[4, 2, 5, 7, 8, 5]


In [29]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [30]:
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


#Check characteristics of existing array

In [48]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [35]:
#Dimension of array
arr.ndim

2

In [36]:
#Shape of array
arr.shape

(2, 4)

In [37]:
#Size of array
arr.size

8

In [49]:
arr.dtype

dtype('int64')

#Create array based on requirements

In [38]:
#Array with zeros
z = np.zeros((5,9))

In [39]:
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [47]:
z.dtype

dtype('float64')

In [40]:
#Array with ones 
one = np.ones((2,6))

In [41]:
print(one)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [62]:
#Array with predifined same values 
t = np.full((3,6),12)

In [63]:
print(t)

[[12 12 12 12 12 12]
 [12 12 12 12 12 12]
 [12 12 12 12 12 12]]


In [61]:
t.dtype

dtype('<U6')

In [72]:
#Range array
arr = np.arange(1,23,1)

In [73]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22])

In [74]:
arr = np.arange(1,23,4)
print(arr)

[ 1  5  9 13 17 21]


#Array slicing :

In [108]:
arr = np.array([[4,6,2,4],[9,7,1,0],[3,1,0,9],[4,3,7,1]])
print(arr)

[[4 6 2 4]
 [9 7 1 0]
 [3 1 0 9]
 [4 3 7 1]]


In [109]:
arr[2,2]

0

In [110]:
#First row
arr[0,:]

array([4, 6, 2, 4])

In [111]:
#Last column
arr[:,3]

array([4, 0, 9, 1])

In [87]:
arr[0:3,0:3]

array([[4, 6, 2],
       [9, 7, 1],
       [3, 1, 0]])

In [90]:
arr[1:,:]

array([[9, 7, 1, 0],
       [3, 1, 0, 9],
       [4, 3, 7, 1]])

In [91]:
arr[1:3,1:3]

array([[7, 1],
       [1, 0]])

In [92]:
arr[1:,0:2]

array([[9, 7],
       [3, 1],
       [4, 3]])

In [93]:
#Flattening
arr = np.array([[4,6,2,4],[9,7,1,0],[3,1,0,9],[4,3,7,1]])
print(arr)
x = arr.flatten()
print(x)

[[4 6 2 4]
 [9 7 1 0]
 [3 1 0 9]
 [4 3 7 1]]


In [100]:
#Reshaping
arr = np.array([[4,6,2,4],[9,7,1,0],[3,1,0,9],[4,3,7,1]])
print(arr)


[[4 6 2 4]
 [9 7 1 0]
 [3 1 0 9]
 [4 3 7 1]]


In [101]:
arr2 = arr.reshape((8,2))
print(arr2)

array([[4, 6],
       [2, 4],
       [9, 7],
       [1, 0],
       [3, 1],
       [0, 9],
       [4, 3],
       [7, 1]])

In [104]:
arr3 = arr.reshape((2,8))
print(arr3)

[[4 6 2 4 9 7 1 0]
 [3 1 0 9 4 3 7 1]]


In [107]:
arr4 = arr.reshape((16,1))
print(arr4)

[[4]
 [6]
 [2]
 [4]
 [9]
 [7]
 [1]
 [0]
 [3]
 [1]
 [0]
 [9]
 [4]
 [3]
 [7]
 [1]]


In [ ]:
#This will generate error 
arr4 = arr.reshape((5,6))
print(arr4)

#Practice code :
 
 create 1 numpy array with dimensions 4,5 : having values 1

 create 2nd numpy array with dimension 4,5 having values : 34

 check their dimensions and shapes , if both dimensions and shapes are same, print "They both can do operation"

In [64]:
arr1 = np.full((4,5),1)

In [65]:
arr2 = np.full((4,5),34)

In [67]:
if(arr1.ndim == arr2.ndim and arr1.shape == arr2.shape):
  print("They both can do operation")

They both can do operation
